projects:
  core:
    name: AI Engineering Core
    root: ./..
    aliases:
      - core
      - ai-core
      - ai-engineering-core

  demo:
    name: Demo Project
    root: ./demo
    aliases:
      - demo
      - 示例项目

  bi:
    name: BI Platform
    root: ../bi
    aliases:
      - bi
      - BI
      - BI平台
      - 数据可视化
